<a href="https://colab.research.google.com/github/devi25priya/python/blob/main/devipriya_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''import numpy as np   #creating numpy as an array
a=np.aaray([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

a=np.array(["abc",2,True,4.1])
print(a)
print(a.ndim)   #ndim---number of dimensions
print(a.shape)  #shape--rows*columns
print(a.dtype)   #u32 shows mixed datatype,64 if only integers'''

'''a=np.array([["abc",2,True,4.1],[1,2,3,4]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)'''
'''
import numpy as np     #######this should be in the firts line for np#######
'''
'''a=np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)'''

'''a=np.zeros((3,7))    #array of zeros        [[0. 0. 0. 0. 0. 0. 0.]
                                           #  [0. 0. 0. 0. 0. 0. 0.]
                                            # [0. 0. 0. 0. 0. 0. 0.]]

print(a)

b=np.ones((1,4))     #array of ones
print(b)                                  ## [[1. 1. 1. 1.]]

c=np.eye(7)          #create identical matrix
print(c)'''

'''d=np.arange(0,91,9)  #arrange---(start,stop,step)
print(d)             #[ 0  9 18 27 36 45 54 63 72 81 90]
e=np.arange(7,77,7)  #starts from 7 but jump 77 ie upto 70
print(e) '''            #[ 7 14 21 28 35 42 49 56 63 70]

'''a=np.linspace(0,1,5)   #linspace(start,stop,count of split)
print(a)               #[0.   0.25 0.5  0.75 1.  ]
b=np.linspace(0,10,5)
print(b)               #[ 0.   2.5  5.   7.5 10. ]
'''

import numpy as np     #######this should be in the firts line for np#######
'''arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,2])  #indexing 1 is[4,5,6] 2is 6in[4,5,6]
print(arr[:1])   #slicing---[[1 2 3]]
print(arr[1,:])  #[4 5 6]
print(arr.shape)
print(arr.reshape(3,2))
print(arr.flatten())'''  #flattens to one dimension----[1 2 3 4 5 6]
#--operations
'''a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*3)
c=np.array([[1],[2],[4]])      #3*1
d=np.array([6,7,8])          #1*3
print(c+d)
#[[ 7  8  9]
# [ 8  9 10]-----------------BROADCASTING
# [10 11 12]]
e=np.array([1,2,4])
f=np.array([[16],[17],[18]])
print(e+f)'''

#----->aggregate function<-------#
arr=np.array([[1,2],[3,4]])
print(arr.sum())                  #10
print(arr.mean())                 #2.5
print(arr.max(axis=0))            #[3 4]
print(np.median(arr))             #2.5

a=np.array([1,2,3,4,5])
mask=a>3
print(a[mask])                   #[4 5]

10
2.5
[3 4]
2.5
[4 5]
